name: Build_5_18_4

on:
    push:
        branches: [build]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Install Dependencies
          run:  apt install -y curl wget gcc bison make cmake build-essential libncurses-dev bison flex libssl-dev libelf-dev
            
