name: Build_5_18_4

on:
    push:
        branches: [build]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
        - name: Install Dependencies
          run:  sudo apt install -y curl wget gcc bison make cmake build-essential libncurses-dev bison flex libssl-dev libelf-dev fakeroot 
          
        - name: Fetch source
          working-directory: ./kernel          
          run:  |
            wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.18.14.tar.xz
            wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.18.14.tar.sign
            
        - name: Verify Sources
          working-directory: ./kernel
          run: |
            unxz -v linux-5.18.14.tar.xz
            gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 647F28654894E3BD457199BE38DBBDC86092693E
            gpg --verify linux-5.18.14.tar.sign
            
        - name: Extract Tarball
          working-directory: ./kernel
          run:  |
            tar -xvf linux-5.18.14 
            chown -R $(whoami):$(whoami) linux-5.18.14 
            
        - name: Clean Kernel tree
          working-directory: ./kernel/linux-5.18.14
          run: make mrproper             
    
